### ISSUE TITLE
エラーコード:2によるクラッシュが発生した。

### ISSUE THREAD

**Issue by valine3g** [pascalllite/MekanismStellar#11]
forge 1.18.2-40.2.26にて、以下のmod構成時にエラーコード:2が発生しました
以下の構成からMekanismStellar [1.18.2-1.2.0-forge]を除外すると正常に起動するため、おそらく当該modが影響していると思われます。
追記:Mekanism, MekanismGenerators, MekanismStellarの最小構成においても、同様にエラーコード:2が返ってきます。
対応お願いします。

構成:
AppleSkin [2.5.1+mc1.18.2 ]
AttributeFix [14.0.4]
Chat Heads [0.6.1]
Cloth Config v4 API [6.5.133]
Clumps [8.0.0+17 ]
Embeddium [0.3.18+mc1.18.2]
Ferrite Core [4.2.2 ]
Jade [5.3.2 ]
Journeymap [5.9.8]
Just Enough Items [10.2.1.1009]
Mekanism [10.2.5]
Mekanism Stellar [1.18.2-1.2.0-forge]
Mekanism: Generators [10.2.5]
ModernFix [5.18.0+mc1.18.2]
Mouse Tweaks [2.21 ]
Oculus [1.6.4]
Polymorph [1.18.2-0.50]
spark [1.10.38]

**Comment by valine3g** [comment]
他のプレイヤーによる追試の結果、以下のエラーログが出たそうです。
`Caused by: net.minecraftforge.fml.loading.moddiscovery.InvalidModFileException: Missing required field mandatory in dependency (Stellar-1.18.2-1.2.0-forge.jar)`

**Comment by ocho-dashijiru** [comment]
forge:
1.18.2-40.2.26

java:
17.0.12 eclipse adoptium

mod:
Mekanism [10.2.5]
Mekanism Stellar [1.18.2-1.2.0-forge]
Mekanism: Generators [10.2.5]

ログ:
https://mclo.gs/5A7HBB8

怪しいと思う箇所:
上記コメントどおり
`Caused by: net.minecraftforge.fml.loading.moddiscovery.InvalidModFileException: Missing required field mandatory in dependency (Stellar-1.18.2-1.2.0-forge.jar)`

備考:
恐らく最小構成下でのエラーです。
詳しくはログをご覧ください。

**Comment by ocho-dashijiru** [comment]
META-INFの
mods.tomlの
```
[[dependencies.stellar]]
modId = "mekanism"
mandatory = true
versionRange = "10.2.5.465"
side = "BOTH"
[[dependencies.stellar]]
modId = "mekanismgenerators"
versionRange = "10.2.5.465"
side = "BOTH"
```
を
```
[[dependencies.stellar]]
modId = "mekanism"
mandatory = true
versionRange = "[10.2.5,)"
side = "BOTH"
[[dependencies.stellar]]
modId = "mekanismgenerators"
mandatory = true
versionRange = "[10.2.5,)"
side = "BOTH"
```
にしたところ起動できました

**Comment by pascalllite** [comment]
指摘と修正案ありがとうございます。
次回からリリース前に別環境での実行テストを行うようにします。

**Comment by pascalllite** [comment]
https://github.com/pascalllite/MekanismStellar/releases/tag/v1.2.1
修正をリリースしました。
